linters:
  enable:
    - govet
    - staticcheck
    - goimports
    - ineffassign

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  exclude:
    - "error return value not checked"

output:
  formats: 
    - format: colored-line-number
  sort-results: true
